### ISSUE TITLE
Dimensions are too large 

### ISSUE THREAD

**Issue by Nur1995** [WebAhead12/Tic-Tac-Toe#1]

**Comment by julio1703** [comment]
I agree with this issue the Dimensions need to be changed

**Comment by Nur1995** [comment]
![WhatsApp Image 2021-11-25 at 12 13 20 PM](https://user-images.githubusercontent.com/79867892/143448057-6a26f2d6-ce5a-45fb-b63c-54f8dabaf6cd.jpeg)
